---
- name: Enable CredSSP
  ansible.windows.win_shell: Enable-WSManCredSSP -Role Server -Force
  when: '"Server" in ansible_distribution'

- name: Install Remote Desktop Services feature
  win_rds_role:
    role: RDS-RD-Server
    state: present
  become: true
  become_method: runas

- name: Allow Remote Desktop through Windows Firewall
  win_firewall_rule:
    name: "Allow Remote Desktop"
    description: "Allow incoming Remote Desktop connections"
    localport: "3389"
    direction: "in"
    action: "allow"
    enabled: true
  become: true
  become_method: runas

- name: Install Chocolatey
  ansible.windows.win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; 
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  args:
    creates: C:\ProgramData\chocolatey\bin\choco.exe

- name: Load prerequisites
  ansible.builtin.include_vars: software.yml
  tags:
    - software

- name: Install software
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
  with_items: "{{ software }}"
  tags:
    - software

- name: Install Spotify
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
    Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify"
  become: true
  become_method: runas
  tags:
    - spotify

- name: Set PowerShell Core as default shell
  win_shell: |
        $registryPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellCommandVerb"
        Set-ItemProperty -Path $registryPath -Name PowerShell -Value "C:\Program Files\PowerShell\7\pwsh.exe"
      become: true
      become_method: runas

- name: Install NetFx3
  ansible.windows.win_optional_feature:
    name:
      - NetFx3
      - Microsoft-Windows-Subsystem-Linux
    state: present
  tags:
    - wsl

- name: Enable Hyper-V
  ansible.windows.win_shell:
    Enable-WindowsOptionalFeature -Name Hyper-V -IncludeManagementTools
  tags:
    - wsl

- name: Enable WSL
  win_shell: dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
  become: true
  become_method: runas
  tags:
    - wsl 

- name: Check if reboot is required
  ansible.builtin.debug:
    msg: "Reboot required: {{ ansible_reboot_pending | bool }}"
  when: "ansible_reboot_pending is defined"

- name: Notify handler to reboot host (if required)
  ansible.builtin.meta: flush_handlers
  when: "ansible_reboot_pending | bool"
  notify: Restart host

- name: Download and Install the latest Ubuntu distribution
  win_shell: |
    $url = 'https://aka.ms/wslubuntu2204'
    $output = 'C:\temp\Ubuntu.appx'
    Invoke-WebRequest -Uri $url -OutFile $output
    Add-AppxPackage -Path $output
  become: true
  become_method: runas
  tags:
    - wsl 

- name: Set new hostname
  win_hostname:
    name: Android3
  become: true
  become_method: runas

- name: Download Docker Desktop installer
  win_get_url:
    url: https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe
    dest: C:\Temp\DockerDesktopInstaller.exe
  become: true
  become_method: runas

- name: Install Docker Desktop silently
  win_shell: Start-Process -Wait -FilePath "C:\Temp\DockerDesktopInstaller.exe" -ArgumentList "/S"
  become: true
  become_method: runas

- name: Remove Docker Desktop installer
  win_file:
    path: C:\Temp\DockerDesktopInstaller.exe
    state: absent
  become: true
  become_method: runas
  
- name: Restart the host (if required)
  win_reboot:
  become: true
  become_method: runas
  when: "ansible_reboot_pending | bool"

