---
- name: Install PowerShell - Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Install the required pre-requisite packages
      ansible.builtin.apt:
        name: wget,apt-transport-https,software-properties-common
        update_cache: true
        state: latest
      become: true

    - name: Download the Microsoft repository GPG keys
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/config/ubuntu/\
          {{ ansible_distribution_version }}/packages-microsoft-prod.deb"
        dest: /tmp/packages-microsoft-prod.deb
        mode: '0640'

    - name: Register the Microsoft repository GPG keys
      ansible.builtin.command:  # noqa no-changed-when
        cmd: dpkg -i /tmp/packages-microsoft-prod.deb
      become: true

    - name: Install Powershell Package - Ubuntu
      ansible.builtin.apt:
        pkg: powershell
        state: latest
        update_cache: true
        force: true
      become: true

- name: Install PowerShell - Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  block:
    - name: Add repository - Fedora
      ansible.builtin.yum_repository:
        name: microsoft
        description: Microsoft Repository
        baseurl: https://packages.microsoft.com/config/rhel/7/prod.repo

    - name: Install the PowerShell Package - Fedora
      ansible.builtin.dnf:
        name: powershell
        state: latest

- name: Install PowerShell - CentOS/RedHat
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  become: true
  block:
    - name: Add repository - CentOS/RedHat
      ansible.builtin.yum_repository:
        name: microsoft
        description: Microsoft Repository
        baseurl: "https://packages.microsoft.com/config/rhel/7/prod.repo"

    - name: Install the PowerShell Package - CentOS/RedHat
      ansible.builtin.dnf:
        name: powershell
        state: latest

- name: Install PowerShell - Windows
  when: ansible_os_family == "Windows"
  become: false
  block:
    - name: Install Chocolatey - Windows
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey

    - name: Install pwsh - Windows
      chocolatey.chocolatey.win_chocolatey:
        name: pwsh
